### ISSUE TITLE
Interview Template

### ISSUE THREAD

**Issue by anthonygarvan** [18F/data-federation-project#1]
## Introductory comments
- What is the data federation effort all about? What am I looking to get out of it?
This is a collaborative research project with GSA's Office of Products & Platforms and 18F. The goal is to build a toolkit / playbook for undertaking intra-governmental data collection / aggregation projects, such as data.gov, code.gov, and NIEM. Or goal is to find out what works, what doesn't, and what tools are appropriate for what circumstances, in order to accelerate similar efforts in the future.
- Notes & Report will be public
- Any questions before we get started?

## Is there anyone else I should speak with to better understand X?

**Comment by philipashlock** [comment]
Looks good. Here are a few related questions to consider augmenting these:

- What was impetus or driving force for this effort: policy, user needs, etc (perhaps after the first question)
- Why did you choose this architecture or process. Were others tried, etc (after the "data aggregation/distribution" question)
- Who were the relevant stakeholders for this project, how were they identified and convened? (perhaps before the last question)

**Comment by juliaklindpaintner** [comment]
This was the interview template for questions asked of successful data federation projects in Phase 1 of the US Data Federation project. Closing this issue for now as interviews were completed.
