### ISSUE TITLE
Data Federation Spectrum

### ISSUE THREAD

**Issue by anthonygarvan** [18F/data-federation-project#10]
Schema Representation:
- Data Dictionary
- Official, machine readable Schema
- Open Standard

Openness of Data:
- open final data
- open aggregated raw data
- open distributed raw data

Genesis:
- Statutory requirement
- Policy
- 3rd Party
- Practitioner

Ownership / Maintenance:
- Gov - Funded
- Gov - Unfunded, centralized
- Gov - Unfunded, decentralized
- Corporate For-Profit
- Corporate Non-Profit
- Standards Body

**Comment by juliaklindpaintner** [comment]
These seem to be notes that led to the [Data Federation Framework](https://github.com/18F/data-federation-project/blob/master/DataFederationFramework.md), informed the [Maturity Model](https://github.com/18F/data-federation-project/blob/master/DataFederationFramework.md#the-data-federation-maturity-model), and were used to [classify projects](https://github.com/18F/data-federation-project/blob/master/summary.csv) interviewed in Phase 1. Closing issue for now as I believe this work is complete.
