### ISSUE TITLE
Evaluate Integration with Colyar System (Montana)

### ISSUE THREAD

**Issue by mheadd** [18F/data-federation-project#105]
## User story
As a project member, I want to understand how the Colyar system might integrate with the django-validation tool so that we can partner with states using Colyar systems. 
  
## Acceptance criteria
- [x] Conduct interview / call with Colyar
- [x] Log into Montana's system and review UI and functionality
~- [ ] Develop high-level overview / requirements to integrate with Colyar system~

**Comment by mheadd** [comment]
Prep for call with Colyar
Log in to Montana’s system with credentials from Bitsey

**Comment by amymok** [comment]
>Log into Montana's system and review UI and functionality

I went thru the verification report page and capture some screens here:
https://docs.google.com/document/d/1Nlj0bA--6jKUPaIjxLQU-ptzMHLl7HIPMEFtMY4I0-w/edit

**Comment by amymok** [comment]
>Develop high-level overview / requirements to integrate with Colyar system

We gave a demo to Colyar on how our API looks like, and what input and output we are expecting.  We didn't have a concrete timeline yet, but we have a path forward. Colyar will proceed with a test environment to see how they can integrate.  And we received a few questions from them that we need to visit as well.
