### ISSUE TITLE
Figure out long term hosting and O&M strategy for FNS use case (or another approach)

### ISSUE THREAD

**Issue by philipashlock** [18F/data-federation-project#107]
## User story
As an FNS stakeholder, I want to understand the different deployment, hosting and maintenance options for the data validation service so that I can deploy it for states and school districts to use in the Fall of 2019.

## Acceptance criteria
- [x] Assemble information on different hosting options for FNS data validator
- [x] Get pricing information from cloud.gov team

**Comment by mheadd** [comment]
2 things that will definitely be need are an ATO (either from the TTS authorizing official, or from FNS) and the identification of funds to cover the cost of hosting / maintenance.

**Comment by mheadd** [comment]
from @amymok:

Here's a reference to cloud.gov info for long term hosting:
https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1550098234005200

**Comment by mheadd** [comment]
I started a summary of the different deployment, hosting & maintenance options [here]([url](https://docs.google.com/document/d/1MPSXYL2i4nYGrIRBMRtOeOZmGstX4JWk-QTSZp9kbrw/edit#)).

**Comment by mheadd** [comment]
[Pricing options](https://docs.google.com/spreadsheets/d/19TXCnLyAJEa7q2fVE3M3O-mag5LHEgx2GsMMem17nPo/edit#gid=0) for cloud.gov.

If we assume FISMA Low (will need to verify) then the annual cost for cloud.gov hosting would roughly $25-30k / year. This also assumes 3-9 GB of RAM is sufficient for the FNS data validation service. @amymok is that a reasonable assumption?

**Comment by amymok** [comment]
@mheadd That looks good to me.
