### ISSUE TITLE
Variables in Error Message

### ISSUE THREAD

**Issue by amymok** [18F/data-federation-project#110]
## User story
As a tool provider, I want to include variables in error message so that user can better understand which value is incorrect. 
  
## Acceptance criteria
- [ ] User will see the actual value in the error message in addition to the field name
- [ ]
- [ ]

**Comment by amymok** [comment]
The use case that FNS is looking for is to do a direct substitution and also perform some operations to get a value in the error message.

Some examples for context:
- Direct substitution:
  [Message for Error Code 71](https://github.com/18F/usda-fns-ingest/blob/master/usda_fns_ingestor/usda_sql_rules.yml#L821-L825)
  `[ x ] ` is to be replaced by `[ S41B_free_doc_stud ]`

- Operation before substitution:
  [Message for Error Code 40W]( https://github.com/18F/usda-fns-ingest/blob/master/usda_fns_ingestor/usda_sql_rules.yml#L412-L416).
  `[ x ]` is to be replaced by `[ S41B_free_doc_stud / S41A_free_doc_apps ]`

The direct substitution is currently being supported.  Simply by putting curly bracket around the variables, the replacement will get done, i.e. `{S41B_free_doc_stud}.  `django-data-ingest` uses the String Formatter `format` method to perform it, see code [here](https://github.com/18F/django-data-ingest/blob/master/data_ingest/ingestors.py#L253).

The operation before substitution is not supported, and will take some more thoughts on it.  A few things I tried to explore:
- Use of f-string since operations can be done inside the f-string
  - This option may not work.  The row data comes in a dictionary with key/value pairs `row_dict`, where the keys are the name of the variables.  This works perfectly for `format` method, since you can convert them into arguments for the `format` method.  But if you need to do it in f-string, we will require to access actual variables, i.e. `S41B_free_doc_stud` needs to be a variable.  Another option would be to make use of `row_dict`, and we access the value by key, i.e. `row_dict["S41B_free_doc_stud"]`.  This means we will need to parse through the message string, and replace each variable to access the dictionary of this variable.  i.e. instead of `{ S41B_free_doc_stud / S41A_free_doc_app }` it will need to be `{row_dict["S41B_free_doc_stud"] / row_dict["S41A_free_doc_app"]}`.  Then we will need to use `eval` to convert a string we put together into f-string.
  - Other options:
    - adding variables to `locals` or `globals` dynamically, which is not a very good practice
    - requiring the error message to include the use of `row_dict[ x ]` instead of just plain `x` for each variable in the rules file, but this seems really weird
  - Questions to think about:
    - Are we introducing security concern by using `eval`?  This rules file is supplied by organization itself, not something user entered through an API though.
   - This still seems like a hack
   - `format` also has a lot of functionalities that come with it, are we allowing it right now, if so, this may break because of the conversion to f-string

- Create customized string formatter (inherited from the `string.Formatter`)
  - I haven't review string.Formatter in depth, but here's my thought:
    We can parse through each field that needs substitution and parse to understand if it is an expression, we will `eval` it first, and then replace it back, and may let the parent formatter to take care of the rest of the formatting
  - Questions to think about:
    - Are we introducing security concern by using `eval`?  This rules file is supplied by organization itself, not something user entered through an API though.
    - More time will be needed to understand the string formatter

There is also the step to cast values because numbers may be coming from csv format, and numbers are kept as string.

Other easier options that I am not thinking about?

**Comment by tbaxter-18f** [comment]
Amy, are the error codes per datafile type or per project?

**Comment by amymok** [comment]
Yes.  Error codes specified by the project in the rules file.  This is also specifically for doing SQL rules and JSON rules.

**Comment by tbaxter-18f** [comment]
I'm not sure I fully grasp this, but if it's per-project and stable across uploads, we could have a dict in the project settings that allows the ability to override the defaults... then, when constructing the error message, we could pull from that. Something along the general lines of 
```
msg = 40w if 40w in settings else "Default message"
```
Plausible?

**Comment by amymok** [comment]
I am trying to make a feature generic that can be used by other projects, let me try to explain with more context here:

Let say a csv file looks like this and we would like to validate:

category,budget,spent
pencils,500,400
red tape,2000,2300

And we can have a rule like so:
```
- error_code: '1'
  check_origin: NEW check
  code: budget > spent
  columns: [budget,spent]
  message: 'Buying {category} was spent more than budgeted, overspent by {spent / budget * 100}%'
```
In the django-data-ingest, it will process one row at a time.  And the 2nd row will trigger an error.  So it will gather all that information and create an error object with the data above in `row_validation_error` function [here](https://github.com/18F/django-data-ingest/blob/master/data_ingest/ingestors.py#L244-L258).

Right now `{category}`will be replaced with red tape because of how it is being implemented, but `{spent / budget * 100}` is an expression not just a variable, so it will give out a KeyError.  So I am seeing if I can create a feature that allows that expression to be evaluated and give out the answer based on all the information given.

**Comment by amymok** [comment]
This is done for the scope we defined.  Another new item is created to capture the new request to include choosing precision for the values being calculated.
