### ISSUE TITLE
Evaluate system integration with KN-CLAIM (Kansas)

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/data-federation-project#111]
## User story
As a project member, I want to understand how the KN-CLAIM system might integrate with the django-validation tool so that we can partner with states using custom solutions. 
  
## Acceptance criteria
- [x] Review files that Kansas is getting error messages with
- [x] Confirm that all errors are included in the data validation tool from FNS and MPRO
- [x] Create plan for implementation

**Comment by amymok** [comment]
>Confirm that all errors are included in the data validation tool from FNS and MPRO

The tool does have all the checks from FNS.

Janis@FNS and Julie@Kansas are checking notes on this.  MPRO have checks that are specific for the mountain-region that may not be relevant for other states.  So we may not include them in the validation check, will double check with them.

**Comment by amymok** [comment]
>Create plan for implementation

The tool has all the FNS checks already.

Will need to check with Janis to see if any MPRO checks need to be implemented

**Comment by juliaklindpaintner** [comment]
@amymok I think this looks good to close out, with the caveat that I think there still isn't a clear plan for implementation since we don't know what their status is. As we discussed, we might want to have a call with them next week to find out how the 2-part submission process works, etc. I'm fine if you want to close this out and open a new, more specific issue to address that.

**Comment by amymok** [comment]
@juliaklindpaintner You are right.  Yes, definitely we need have that discussion with them, and explore ways to implement that.  I opened this issue for that purpose, feel free to add/edit it if I miss anything.
https://github.com/18F/data-federation-project/issues/125
