### ISSUE TITLE
More clearly define goals for this work in Phase 3

### ISSUE THREAD

**Issue by philipashlock** [18F/data-federation-project#113]
## User story
As a team member, I want to answer the question "What does success at the end of Phase 3 look like?" so that I can identify steps to take and measure progress towards the overarching goals. 

Possible places to focus might be
- Website update
- Building on maturity model, case studies
- Creating a business plan for the ingest tool
- Developing documentation resources (both relating to our use cases and others that already exist in the world)
Etc.

## Acceptance criteria 
- [x] Plan a goal-setting workshop with outside facilitator
- [x] Participate in goal-setting workshop
- [x] Summarize output of workshop into clear goals and identify steps we can build in to future sprints

**Comment by juliaklindpaintner** [comment]
* We held our session on 2/12/19 with the help of Elizabeth Ayer using a [Mural](https://app.mural.co/t/gsa6/m/gsa6/1549462451079/fe30e885a920c52bec7c7089fa8cad37ed782655). 
* I transferred the output from the mural over to a [Google doc](https://docs.google.com/document/d/1ZHhWNQgxgz52v-6-UYxu7dg7JKYnqP-iTu49Qdt4cUA/edit#) and began a summary.
* @philipashlock has suggested creating a one-pager with our goals that can be referred to during sprint planning to ensure our tasks are laddering up to the larger vision.
