### ISSUE TITLE
Interview Template: Person of Interest

### ISSUE THREAD

**Issue by anthonygarvan** [18F/data-federation-project#12]
## Introductory comments
- What is the data federation effort all about? What am I looking to get out of it?
This is a collaborative research project with GSA's Office of Products & Platforms and 18F. The goal is to build a toolkit / playbook for undertaking intra-governmental data collection / aggregation projects, such as data.gov, code.gov, and NIEM, where data is collected from entities over which you do not have direct authority. We call these federated data efforts. Or goal is to find out what works, what doesn't, and what tools are appropriate for what circumstances, in order to accelerate similar efforts in the future.
- Notes & Report will be public
- Any questions before we get started?

**Comment by juliaklindpaintner** [comment]
This is the interview template used in Phase 1. Closing this issue for now as interviews are complete.
