### ISSUE TITLE
Check data against their acceptable range and type

### ISSUE THREAD

**Issue by amymok** [18F/data-federation-project#124]
## User story
As a rules maintainer, I want to explore ways to check data against their acceptable range and type so that we can throw an error when the data doesn't include valid data. 
  
## Acceptance criteria
- [ ] Explore current tool to see if this functionality exists
- [ ] Tailor or implement this functionality for FNS
- [ ] Test with existing test cases

**Comment by cantsin** [comment]
I believe we already do this for ReVAL; please re-open if this is in error or refers to something else. Thanks.
