### ISSUE TITLE
Draft a framework for measuring impact and implementation challenges of potential use cases

### ISSUE THREAD

**Issue by ethanheppner** [18F/data-federation-project#129]
## User story
As a member of the U.S. Data Federation, I want to develop a framework measuring impact and implementation challenges of potential use cases so that we can better understand the needs, incentives, and timelines future use cases might have if they work with us.

## Acceptance criteria
- [x] Draft agenda for meeting with FNS to learn how they are quantifying impact of implementing their validation service with the help of the Django Data Ingest Tool, how much time and what resources they need in order to continue to develop their service, and what the most significant implementation challenges they see are.
- [x] Meet with FNS and synthesize feedback.
- [x] Learn about how the Federal Data Strategy approaches measuring impact and implementation costs of each of the use cases they are exploring.
- [x] Inventory how we spent our time on the FNS use case.
- [ ] Finalize draft framework for measuring impact and implementation costs based on our input from FNS, the Federal Data Strategy, and our own work so far on FNS and research with other use cases.

**Comment by juliaklindpaintner** [comment]
This issue has been partially addressed through the creation of this [spreadsheet of case studies](https://docs.google.com/spreadsheets/d/1kxndgG-DxRHw_n7rXq5OYtva5VDkzVIXBKd-C27oJSE/edit#gid=1629371946) and this set of [interview questions](https://docs.google.com/spreadsheets/d/1kxndgG-DxRHw_n7rXq5OYtva5VDkzVIXBKd-C27oJSE/edit#gid=1629371946). Closing in favor of actionable issues.
