### ISSUE TITLE
Narrow down potential use cases and document them in the context of the evaluation framework (Issue # 129)

### ISSUE THREAD

**Issue by ethanheppner** [18F/data-federation-project#130]
## User story
As a member of the U.S. Data Federation, I want to develop a narrow down and document our potential use cases so that we can more easily evaluate which use case is the best fit for the next phase of our project given it's potential impact and implementation challenges.

## Acceptance criteria
- [ ] Present a rough list of possible use cases, team to pick between 5 and 10 to critically evaluate using the framework established in #219.
- [x] Create spreadsheet for the purpose of evaluating selected use cases and populate with information gathered from previous research.
- [x] Schedule calls with the identified agencies as needed with the objective of getting a more robust understanding of the impact and implementation challenges.
- [ ] Finalize spreadsheet and prepare a facilitated discussion about a second use case.
- [x] Decide on second use case.

**Comment by juliaklindpaintner** [comment]
Closing this in favor of #128.
