### ISSUE TITLE
Understand USDA ATO requirements for FNS Data Validation service

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/data-federation-project#159]
- [x] Have call with Joe Binns from USDA CIO
- [x] Receive documentation from Joe Binns on requirements for ATO
- [x] Find out from Joe Binns whether we can leverage the Forest Service work
- [x] Identify which parts of the ATO package creation we can help with

**Comment by mheadd** [comment]
Per Joe Binns:

> Yes we did make contact with FS; and both security teams came to the conclusion that FNS will need a separate ATO for cloud.gov.

**Comment by mheadd** [comment]
For our next grooming session, I'd suggest we break off the last acceptance criteria above:

> Identify which parts of the APO package creation we can help with

Into a separate card. Ideally, that card would be for scoping the 18F engagement with FNS to help them complete the ATO and get the validator into production on cloud.gov. /c:; @juliaklindpaintner

**Comment by juliaklindpaintner** [comment]
That makes sense to me!
