### ISSUE TITLE
Ramp up on Federalist, Cloud, Login, and other models for sustaining a tool/service

### ISSUE THREAD

**Issue by sawtoothwave** [18F/data-federation-project#160]
- [x] Review documentation from Julia
- [x] Follow up with Cloud.gov...
- [x] Login.gov...
- [x] Federalist...
- [ ] eRegs (talk to Will S)
folks to get to speed on existing models

**Comment by tbaxter-18f** [comment]
I think this may tie in closely with the work I'm doing to create a reusable starter install.

**Comment by sawtoothwave** [comment]
o rly
let's chat about it!

**Comment by juliaklindpaintner** [comment]
I think the eRegs conversation is no longer a priority. Closing this issue for now.
