### ISSUE TITLE
Set up interviews with at least 3 more federated data case studies

### ISSUE THREAD

**Issue by ethanheppner** [18F/data-federation-project#169]
Interviews can either be with FDS Proof Points (see email from Bryant on April 10th) or other efforts identified in our [case studies sheet](https://docs.google.com/spreadsheets/d/1kxndgG-DxRHw_n7rXq5OYtva5VDkzVIXBKd-C27oJSE/edit#gid=783944950), as long as the effort is a federated data effort.

**Comment by juliaklindpaintner** [comment]
Scheduled interviews with FEMA and WZDx for 4/26 and 5/1, respectively. Question doc here: https://docs.google.com/document/d/1ikgBeH2M7MjiNunIpbgTt_EP9HjtAhACyDcFz6vyYjk/edit?ts=5ca4fbc6#

Scheduling with others.
