### ISSUE TITLE
Mike to build [reduce complexity/enhance features] spectrum kinda thing in Mural

### ISSUE THREAD

**Issue by sawtoothwave** [18F/data-federation-project#172]
Try to outline a balance between future opportunities to either increase the production-readiness of the tool, or increase its featureset, to see how we'd expect to allocate resources.

**Comment by juliaklindpaintner** [comment]
[Mural here](https://app.mural.co/t/gsa6/m/gsa6/1556635545965/80f0ff580af834307d29211de857c1de2e432599)
