### ISSUE TITLE
Draft list of anticipated support needs to help FNS put together a PWS

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/data-federation-project#174]
- [x] Draft list of anticipated support needs to help FNS put together a PWS
- [x] Circulate with team
- [x] Send to FNS

**Comment by mheadd** [comment]
Draft list of support needs [can be found here](https://docs.google.com/document/d/17XIcNH7fimn_IiNwtVAWzgOG7PzA0V3ltvIsBaJtVVY/edit#).
