### ISSUE TITLE
Talk to security leads about considerations moving from prototype to production

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/data-federation-project#176]
- [x] Reach out to 18F security leads
- [x] **Create security checklist based on https://before-you-ship.18f.gov**
- [x] Have a conversation to learn about considerations
- [x] Share with team

**Comment by amymok** [comment]
This kind of revolve into looking at https://before-you-ship.18f.gov to determine what is needed for security and production ready. Before sharing with the team.
