### ISSUE TITLE
Establish mailing list for U.S. Data Federation

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/data-federation-project#178]
- [x] Create mailing list with contacts in our [spreadsheet](https://docs.google.com/spreadsheets/d/1kxndgG-DxRHw_n7rXq5OYtva5VDkzVIXBKd-C27oJSE/edit#gid=0)
- [x] Draft initial message
- [ ] Send initial message

**Comment by juliaklindpaintner** [comment]
@philipashlock I'm not sure how to establish a mailing list, but I'm assuming it would make sense for it to be associated with you or at least OPP rather than 18F. I will finish adding a few more contacts to our [spreadsheet]() today and then that should be ready to set up. I'm sure you have additional names you'll want to add. 

### Draft initial email for this mailing list: 
**Proposed date to send:** May 29 (after holiday weekend)
**Subject line:** News from the U.S. Data Federation
**Message body:** 
Hello! 

You are receiving this email because you have contributed to, consulted on, or expressed interest in the work of the U.S. Data Federation. This initiative, funded by the 10x program at GSA, is focused on developing reusable tools and documenting and sharing repeatable processes to make managing federated data efforts easier. For an overview of our work, check out this [blog post](https://18f.gsa.gov/2019/03/05/the-us-data-federation/) or our [recorded webinar](https://digital.gov/event/2019/04/17/an-introduction-us-data-federation/).

As we reach the end of our Phase 3 funding through the 10x program, we are creating this mailing list to help us maintain the connections made throughout this phase and continue to share our work. A few updates we want to provide today: 

* The project on which we collaborated with the USDA's Food & Nutrition Service has been featured as a [Proof Point](https://strategy.data.gov/proof-points/2019/05/17/supercharging-data-through-validation-as-a-service/) by the Federal Data Strategy. 
* We are currently preparing to pitch for Phase 4 funding to continue the development of our [reusable data validation tool](https://github.com/18F/django-data-ingest) to make it maximally reusable and adoptable by data practitioners across government. **If you see value in this work, please drop us a line!**

Many thanks and best wishes, 

10x U.S. Data Federation Team

**Comment by mheadd** [comment]
@juliaklindpaintner - You can set up a Google Group using these instructions: https://handbook.18f.gov/google-groups/

I went through this once before, so if you have questions or I can help just let me know.

**Comment by juliaklindpaintner** [comment]
Mailing list has been set up.
