### ISSUE TITLE
Interview: Rachel Bloom

### ISSUE THREAD

**Issue by anthonygarvan** [18F/data-federation-project#22]
## What experience do you have that might be relevant to this effort? (e.g., work with open data standards, participation in gov data collection across organizational boundaries, etc.)
[previous research arose from] geothink, work done as undergrad @ McGill at Geothink . Had a Geothink partner city interested in knowing what standards exist to publish open data. Started out making catalog of standards that existed for such data (had to be open & for specified domains). City wasn't able to disentangle important from non-important info. Then the  idea came up to create a dashboard. Made an attempt and what emerged was a systematic set of metrics. open data standards directory is name of dashboard and published by geothink and center for government excellence. Evaluating different kind of open data standards for specific "high value" types of open data. 

Also did own work as a student, interviewing preferences for open data standards and types of knowledge about data standards. One finding is that people have different definitions for talking about standards. Interviewed 13 cities in U.S. Mostly open data leads & some other titles. Now works at OpenNorth (montreal) non profit that specializes in civic tech & open data. Now mapping openness onto smart city development. Asks the question: what does it mean to be an open smart city? 

# What works?
"It's really hard" to answer because different objectives among different actors. Metrics for interoperability of data for municipal data encode a lot of what is good / promoted in these effort. Check it out! metrics themselves bring to light key things that open data standards should incorporate into their development.

## What efforts are you aware of that fit this category?
Started at open data standards directory. I evaluated 27 standards, but now over 60 now in the directory.

## Do you have contacts in those efforts who we could reach out to?
- skipped 

## Are data standards a good idea?
I like this question because part of this type of research is innovation bias (i.e., people expect that others want to adopt new stuff). But is it actually a priority? Is there a perceived need / benefit by potential adopters? Question about whether standards are good is better suited for adopters because these standards will serve their larger objective.  

"I clearly think think they're worthwhile." Any approach that makes data more open / transparent / improves access and ease of sharing information with general public that doesn't compromise privacy/security is good to me. More tools required? "I think that's very advanced for the work I've been seeing" 

## What do you think are the primary challenges of these types of efforts?
interviewed open data challenges for adopters at cities - time & resource constraints were the primary cited. Interoperability "is even more than a technical obstacle but is a coordination issue as well." Interoperability = seamless transfer of data and information. Do specifically look at data that tries to open the data as much as possible. They just need time to think critically about this kind of stuff. Even if you do provide resources, there needs to be a learning process. People need time to reflect and be informed and to troubleshoot the problems in a critical way. More time to educate themselves.
 
Interviewees typically decision makers in publishing open data & interested in data standards. Usually managers / project coordinators, and less interviewees were involved in technical details of adopting standards.

**Comment by juliaklindpaintner** [comment]
Interview complete; closing issue.
