### ISSUE TITLE
Interview: data.gov.ie

### ISSUE THREAD

**Issue by anthonygarvan** [18F/data-federation-project#23]
## Introductory comments
- What is the data federation effort all about? What am I looking to get out of it?
This is a collaborative research project with GSA's Office of Products & Platforms and 18F. The goal is to build a toolkit / playbook for undertaking intra-governmental data collection / aggregation projects, such as data.gov, code.gov, and NIEM. Or goal is to find out what works, what doesn't, and what tools are appropriate for what circumstances, in order to accelerate similar efforts in the future.
- Notes & Report will be public
- Any questions before we get started?

## What is data.gov.ie in your own words?
it's the national open data portal for irish government, provides access point 
5.5k datasets from across publishers (doesn't host or store)
a lot of different harvesters
federated approach

## What was impetus or driving force for this effort: policy, user needs, etc (perhaps after the first question)
around 2009 / 10 / 11, open data coined. Deirdre working at research institute, but a lot of community / citizen / local government sees it as very important. In 2013/14 at a national level the gov as part of open gov partnership committed to national data portal. Since 2014, national open data portal policy. They worked to document what is open data, what is important. From 2014 it was making more data available. Then different orgs came onboard. What was defined early on was public bodies working group. A lot of geospatial / stats community. Came together to define standards / documents. Available in references section of data.gov.ie. Technical framework document defined. Over last 2-3 years, more awareness of open data, emerges as key element of lots of other open policies. Open data governance board established, made up of reps outside of gov, provides guidance & advisory role for open data as well. Recently ranked top in europe for open data.  

## In building open data portal, what were the biggest challenges, and what went smoothly?
there has been an evolution of the overall initiative. Could we have fast-forwarded that evolution? (unlikely) need to grow understanding as a country, as a government. When portal was first launched, used ckan, couple of datasets lying around. Next big step was drupal / ckan. Past couple years there's been a lot of customization. Focus on 13/14/15 was raising capacity within the public sector themselves. 3-4 ppl are the "open data unit". From tech level- revamping portal again, continuing to add different features. Definitely emphasis on quality, real time data, APIs now. from actual site. Last few months: few high profile real time data available as APIs. e.g., bills / policies api. 

## What tools and technologies do you use for this effort?
d-cat. w3c recommended. It has become the defacto metadata standard for open data catalogs. d-cat application protocol. +dcat-ap. ckan -> drupal+ckan -> updating to current core ckan, more efficient backend.

## Why did you choose this architecture or process. Were others tried, etc (after the "data aggregation/distribution" question)
it's a hybrid - manually update via user interface, api upload, 3rd is via harvesters. Now harvest from 14 different sources, based on arcGIS system. Pull in from data sources that are already there. Recommended if the data volume is large. Also (4), data audit tool, used for pre-publication stage.
audit tool to build data. Also asks questions - should they publish it or not?

visualizations- for catalog itself, there are previews for all different data types. Lot of data in json-stash stmx data, format (statistical data). More to give user impression, there's lot of data here, explore!

## What are the political and organizational dynamics of collecting this data?
"very much the role of the open data unit" -> would work closely with open data bodies, explaining what is involved, disseminating awareness. From their side, make it as easy to publish as possible. Make it easy for the public body to publish. Supporting & guiding. Another thing is to show examples and use cases, show how other public bodies do it. Public bodies working group. Focus around the impact of open data. "The more stories, examples, use cases, the better" started open data impact series. Discuss open data impact in panels. Large banks, insurance companies, etc., see how it can have an impact in decision making and processes or in opening markets. "As a community internationally, we need to be doing wider studies of impact of open data."

## Who else is working on tooling?
- portal at datadoor
- insight center
- vienna, open data portal watch
- European data portal
- group in Belfast

**Comment by juliaklindpaintner** [comment]
Interview complete; closing issue.
