### ISSUE TITLE
As a policy-maker, I want to understand where the project is going so that I can know how to leverage it. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/data-federation-project#38]
## User story
As a policy-maker, I want to understand where the project is going so that I can know how to leverage it. 
  
Project communications related items: 

## Acceptance criteria
- [x] Due-diligence / outreach with other policy-makers is communicated
- [x] One-pager is shared (or overview deck)
- [x] Announced on the listserv / open data list / open cabinet list, etc.

**Comment by OpenGlobe** [comment]
Overview deck is [here](https://docs.google.com/presentation/d/1lnX91_bw19HSfaKscR0JAGglr6IFmHxUfQijdf4XE7c).

**Comment by juliaklindpaintner** [comment]
Closing this issue given the outreach and comms work we've been doing.
