### ISSUE TITLE
Set up kick off with Montana volunteer partner

### ISSUE THREAD

**Issue by mheadd** [18F/data-federation-project#75]
## User story
As a \<type of user\>, I want \<a goal\> so that \<benefit\>. 
  
## Acceptance criteria
- [ ]
- [ ]
- [ ]

**Comment by mheadd** [comment]
Kansas kick-off is scheduled for Friday 11/30 @ 11 EST

**Comment by mheadd** [comment]
Per call with FNS 11/29 there may be other state volunteers coming out of a conference next week

**Comment by mheadd** [comment]
Kansas kick-off is scheduled for Friday 11/30 @ 11 EST

**Comment by juliaklindpaintner** [comment]
Montana kick-off is scheduled for Thursday 12/20 @ 5pm EST
