### ISSUE TITLE
Identify potential use cases

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/data-federation-project#76]
## User story
As a team member, I want to identify and connect with potential partners so that I can establish use cases for the tool. 
 
## Acceptance criteria
- [x] Conduct outreach via human services portfolio
- [x] Create initial set of screening criteria
- [x] Establish place to capture and organize information on potential use cases

**Comment by mheadd** [comment]
Some thoughts:
* Look for diversity of maturity in data collection efforts
* Look for diversity on ability to adopt technical tooling
* Look for needs to adopt best practices vs. specific tooling.

**Comment by philipashlock** [comment]
Some thoughts: 
- Look for diversity of coverage in terms of representation across the maturity model
- Look for coverage across using capabilities of tools (e.g. data validation vs data aggregation)
- Look for representation to develop and validate good practices and guidance that are tool agnostic (e.g. governance process, standards development, etc)
- Willingness and readiness for a partner to work with us within the timeline of phase 3
- Scale and scope that allows for meaningful deliverables within timeline of phase 3
- Diversity of representation across different levels of government or organization structures, e.g. local/state/federal vs federal to federal.

**Comment by mheadd** [comment]
I've reached out to both the State of AK and VT to inquire about data collection requirements from CMS.

**Comment by mheadd** [comment]
I spoke with Ryan Sibley yesterday - she was previously on the FBI Crime Data Explorer project. She has some good contacts at CJIS that might be worth talking to about [how states report crime and criminal justice data](http://www.jrsa.org/sac/) up to the federal government. I'm going to try and set up a call with the folks she recommended, to introduce them our work and see if there are any opportunities to identify a potential use case. /cc: @juliaklindpaintner @amymok @ethanheppner

**Comment by mheadd** [comment]
Also reaching out to CDC to see if there is anyone there involved in their state/local data collection efforts that we can connect with.

**Comment by mheadd** [comment]
@philipashlock Has reached out to Matthew Greene and Ross Santy at the Department of Education to explore possible use cases. Interested in following up with them on the project @ethanheppner mentioned about standardized reporting for student grades.

**Comment by juliaklindpaintner** [comment]
@juliaklindpaintner set up a meeting with Gil Alterovitz to discuss possible VA use case.

**Comment by mheadd** [comment]
Reach out to CoPs with
Prep for convo with CMS 
Another HHS possibility?

**Comment by mheadd** [comment]
I'm submitting a PR to create a separate issue template for potential case study partners. That will allow us to track our contacts with other organizations and use issues and labels to organize them.

**Comment by mheadd** [comment]
We can now track all potential use case opportunities using the [Case Study](https://github.com/18F/data-federation-project/labels/Case%20Study) label.
