### ISSUE TITLE
Develop promotional materials for partners

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/data-federation-project#77]
## User story
As a potential partner, I want to understand what the data federation project is so that I can assess whether I can particulate and potentially benefit.
  
## Acceptance criteria
- [x] Reviewing existing materials from Phase 1 and 2.
- [x] Develop introductory narrative to data federation project, to capture the problem the effort is meant to address.
- [x] Check with other 10X teams to see what form their promotional materials have taken
- [x] Get feedback from 18F human services portfolio participants. 
- [x] Write a case study of FNS to demonstrate value of tool to both data providers and aggregators.
- [x] Export final PDFs to share.

**Comment by mheadd** [comment]
Would we want this to also be useful for socializing the work with those involved in the federal data standards work? Or should that be done in a separate document? /cc: @philipashlock

**Comment by juliaklindpaintner** [comment]
We developed a [simple project overview](https://docs.google.com/document/d/1_-u4cxv1RH92DPF8TFgZrJMnRyNBlBFAFk49C9f_3SI/edit?userstoinvite=john.jediny@gsa.gov&ts=5c002e13&actionButton=1#), a [project overview with a case study](https://docs.google.com/document/d/1Yj3-jejNWs2jZZodJcctcyRvn_o-oBmktykOGCUDltg/edit#), and a [simple intro presentation](https://docs.google.com/presentation/d/1_4-oSzm9O_czcJlNgdcViEEop4pw8h_j-GevBVNLmb0/edit#slide=id.g463b654acf_0_18). I shared the deck with my design critique group and received the following questions/feedback: 

- Who is the audience for this presentation? When would this be used?
- Where is the branding from? Is it meant to present as a new service/product? If offered by 18F, should the branding align more with 18F branding?
- How is this related to data.gov? The website URL makes US Data Federation appear as a subdomain of data.gov, but US Data Federation seems to have a wider-reaching scope?

**Comment by juliaklindpaintner** [comment]
I believe this work is complete, pending any change in messaging that we identify as necessary to our work. The only thing that remains is to discuss how these artifacts should be stored/shared.

**Comment by juliaklindpaintner** [comment]
All materials saved in Drive in the [Promotional Materials](https://drive.google.com/drive/folders/14Do_2mYTHRs3hR0RkKltstXk13ZqQSQO) folder and attached here.
[10xDataFederation_Overview_FNS Case Study.pdf](https://github.com/18F/data-federation-project/files/2829903/10xDataFederation_Overview_FNS.Case.Study.pdf)
[10xDataFederation_Overview.pdf](https://github.com/18F/data-federation-project/files/2829904/10xDataFederation_Overview.pdf)
[US Data Federation Intro Deck.pdf](https://github.com/18F/data-federation-project/files/2829905/US.Data.Federation.Intro.Deck.pdf)
