### ISSUE TITLE
Identify Tool Name for Marketing Efforts

### ISSUE THREAD

**Issue by mheadd** [18F/data-federation-project#86]
## User story
As a project team member, I want to be able to conduct outreach to potential partners so that they can easily understand what the data ingest tool is and how it can help them. 
  
## Acceptance criteria
- [x] Convene group discussion on potential names
- [x] Clarify *what* we're naming
- [x] Review document from 10X group on renaming
- [x] Socialize some candidate names for feedback

**Comment by mheadd** [comment]
Internal doc on renaming process  steps: https://docs.google.com/document/d/1zwofh0mZafSIXKLMZw_1vVQfHcVUWI-shcA6uZNoW_8

**Comment by juliaklindpaintner** [comment]
It's called ReVAL 😄
