### ISSUE TITLE
Consider ways of minimizing the need to re-write error messages

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/data-federation-project#87]
## User story
As a FNS, I want to map the data ingest tool output to existing error messages so that I don't have to rewrite error messages for every case.

As the US Data Federation, I want to set up ways to streamline the way error output is mapped to existing systems so that it can be more generalizable  
  
## Acceptance criteria — not sure about these!
- [ ] Look at KS edit-checks and see how they are constructed
- [ ] Write code that maps our errors to theirs?
- [ ] Test?

**Comment by mheadd** [comment]
Impetus was demo for Kansas that raised discussion of how error messages are displayed, field names, etc.
