### ISSUE TITLE
Update US Data Federation website

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/data-federation-project#91]
- [x] Audit the current website 
- [x] Define audience and goals for website
- [x] Identify content to add and to remove
- [x] Implement changes
- [x] Preview changes
- [x] Submit pull request

**Comment by ethanheppner** [comment]
This might be informed by our research on use cases-- we could get other agencies' thoughts on how they see U.S. Data Federation and what they might look for on the website.

**Comment by juliaklindpaintner** [comment]
Have not been working on this, but would like to!

**Comment by juliaklindpaintner** [comment]
@philipashlock @sawtoothwave @ethanheppner here's a first stab at suggested lightweight changes to the website for the interim. These changes are intended to simply ensure that people encountering information about the project from our presentations will see consistent language when visiting our site. We simply want to reflect the current status and thinking. Once we agree on the changes more or less, I can make a new branch of the repo, implement the changes and submit a pull request.

**Homepage** 
- Update banner copy to say "The United States Data Federation is a project focused on making it easier to collect, combine, and exchange data from disparate sources." (or similar)
- Use the structure of the presentation we've been sharing to give the overview of the problem (i.e. what's the problem, why is it hard, what data are we talking about, what's our hypothesis of how to solve it—could use some of the graphics from the deck)

**Initiatives**
- Change title to "Tools & Resources"
- On this page, add one line intro about how we are curating and developing tools and resources here. - Make two categories: "Tools" & "Resources"
- Under Tools, describe the Django Data Ingest and current use case and link to Github repos; potentially list other ideas if we have them
- Under Resources, have the Playbook and Case Studies 

**Participate and Contact**
- Combine into "Get in touch" — pages have the same info anyway

**About**
- Possibly small changes to the copy to bring it up to date. Link to the blog post and webinar. Change the Partner With Us message to reflect who we want to hear from.

**Comment by juliaklindpaintner** [comment]
Changes are implemented and have been merged with the develop branch. Will merge with Master EOD today or Monday.
