### ISSUE TITLE
Blog Post Summarizing Project

### ISSUE THREAD

**Issue by mheadd** [18F/data-federation-project#97]
## User story
As a potential partner, I want a high-level summary that I can easily share with others so that I can advocate to take part in the data federation project. 
  
## Acceptance criteria
- [x] Create issue in blog draft repo
- [x] Write draft of blog post
- [x] Share with 10X team for comment and feedback
- [x] Publish blog post

**Comment by juliaklindpaintner** [comment]
Opened the issue in the blog draft repo: https://github.com/18F/blog-drafts/issues/710

**Comment by juliaklindpaintner** [comment]
This blog post is nearly ready to publish. Just addressing a comment from the 10x team and then will coordinate publish date with @philipashlock and @awfrancisco.

Final draft [here](https://docs.google.com/document/d/10V9RV8QxjfjGcropwY_39JNUV-vV6MXqccGYSsgeOn0/edit#)

**Comment by juliaklindpaintner** [comment]
Blog post is on hold while we align with the Federal Data Strategy.
